config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :accomodations 
  get '/search-listing' => "listing_search#search_listing"

  devise_for :users, controllers: {
    sessions: "users/sessions", 
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    confirmations: "users/confirmations"
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  resources :listings, only: [:show, :index]
  resources :places, only: [:show, :index]
  delete '/remove_listing_image/:id' => "listings#remove_listing_image"

  namespace :admins do 
    resources :amenities
    resources :listings 

    resources :listing_categories
    resources :place_categories
    resources :places do 
      collection do
        post :upload_place_image
      end
    end
  end

  namespace :users do 

        resources :listings do
          collection do
            post :upload_listing_image
          end
          member do 
            get :add_images
          end 
        end
        resources :accomodations do
          collection do
           post :upload_accomodation_image 
         end
         member do 
          get :add_images  
        end  
      end

    resources :accounts
    get '/my-account' => "accounts#my_account"

  end

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/accomodation.rb
class Accomodation < ApplicationRecord
  # belongs_to :listing_category, optional: true
  belongs_to :user, optional: true
  has_many :images, as: :imageable, dependent: :destroy
  has_many :accomodation_amenities
  has_many :amenities, through: :accomodation_amenities
  geocoded_by :full_address
  after_validation :geocode

  mount_uploader :banner_image, ImageUploader

  def full_address
    "#{self.city} #{self.state} #{self.country} #{self.zipcode}"
  end
end

app/controllers/accomodations_controller.rb
class AccomodationsController < InheritedResources::Base
 layout 'listing'
 def new
   @accomodation = Accomodation.new
   @amenities = Amenity.all
 end
 def show
  @accomodation = Accomodation.find(params[:id])
end
private

def set_accomodation
  @accomodation = Accomodation.find(params[:id])
end

def accomodation_params
  params.require(:accomodation).permit(:name, :description, :banner_image, :city, :state, :country, :address, :zipcode, :website, :latitude, :longitude, :email, :contact, :no_of_rooms, :no_of_toilets, :no_of_halls, :user_id)
end
end

app/controllers/users/accomodations_controller.rb
class Users::AccomodationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_accomodation, only: [:show, :edit, :update, :destroy]
  layout 'listing'
  # GET /accomodations
  # GET /accomodations.json
  def index
    @accomodations = current_user.accomodations
  end
  # GET /accomodations/1
  # GET /accomodations/1.json
  def show
   @accomodation = Accomodation.find(params[:id])
 end
  # GET /accomodations/new
  def new
   @accomodation = Accomodation.new
   @amenities = Amenity.all
 end
  # GET /accomodations/1/edit
  def edit
   @accomodations = Accomodation.all
   @amenities = Amenity.all
 end
 def upload_accomodation_image
   @accomodations = Accomodation.find(params[:upload_images][:accomodation_id])
   @image = @accomodations.images.build(image: params[:upload][:image])
   if @image.save!
     respond_to do |format|
       format.json{ render :json => @image }
     end
   end
 end
 def remove_accomodation_image
   @image = Image.find(params[:id])
   if  @image .destroy
    render json: { message: "file delete from server"}
  else
   render json: {message: @image.errors.full_messages.join(", ") }
 end
end
def add_images
 @accomodation = Accomodation.find(params[:id])
end
  # POST /accomodations
  # POST /accomodations.json
  def create
   @accomodation = Accomodation.new(accomodation_params)
   respond_to do |format|
    if @accomodation.save
      format.html { redirect_to users_accomodation_path(@accomodation), notice: 'accomodation was successfully created.' }
      format.json { render :show, status: :created, location: @accomodation }
    else
      format.html { render :new }
      format.json { render json: @accomodation.errors, status: :unprocessable_entity }
    end
  end
end
  # PATCH/PUT /accomodations/1
  # PATCH/PUT /accomodations/1.json
  def update
    respond_to do |format|
      if @accomodation.update(accomodation_params)
        format.html { redirect_to users_accomodation_path(@accomodation), notice: 'accomodation was successfully updated.' }
        format.json { render :show, status: :ok, location: @accomodation }
      else
       format.html { render :edit }
       format.json { render json: @accomodation.errors, status: :unprocessable_entity }
     end
   end
 end
  # DELETE /accomodations/1
  # DELETE /accomodations/1.json
  def destroy
   @accomodation.destroy
   respond_to do |format|
     format.html { redirect_to users_accomodations_url, notice: 'accomodation was successfully destroyed.' }
     format.json { head :no_content }
   end
 end
 private
  # Use callbacks to share common setup or constraints between actions.
  def set_accomodation
    @accomodation = Accomodation.find(params[:id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def accomodation_params
    params.require(:accomodation).permit(:name, :description, :banner_image, :city, :state, :country, :zipcode, :latitude, :longitude, :contact, :email, :website, :address,  :no_of_rooms, :no_of_toilets, :no_of_halls, :user_id, images_attributes: [:id,:image, :imageable_id, :imageable_type, :_destroy])
  end
end

app/helpers/accomodations_helper.rb
module AccomodationsHelper
end

app/views/accomodations/_form.html.erb
<section>
   <div class="container">
      <div class="col-md-10 col-sm-12 col-md-offset-1 mob-padd-0">
         <%= form_for [@accomodation] do |f| %>
         <!-- General Information -->
         <% if accomodation.errors.any? %>
         <div id="error_explanation">
            <h2><%= pluralize(accomodation.errors.count, "error") %> prohibited this accomodation from being saved:</h2>
            <ul>
               <% accomodation.errors.full_messages.each do |message| %>
               <li><%= message %></li>
               <% end %>
            </ul>
         </div>
         <% end %>
         <%= f.hidden_field :user_id, value: current_user.id %>
         <div class="add-listing-box general-info mrg-bot-25 padd-bot-30 padd-top-25">
            <div class="listing-box-header">
               <i class="ti-files theme-cl"></i>
               <h3>General Information</h3>
               <p>Write something general information about your accomodation</p>
            </div>
            <div class="row mrg-r-10 mrg-l-10">
               <div class="col-sm-6">
                  <%= f.text_field :name, id: :accomodation_name, class: "form-control" %>
                  <label>Accomodation Title</label>
               </div>
               <div class="col-sm-6">
                  <%= f.file_field :banner_image %>
                  <label>Banner Image</label>
               </div>
               <div class="col-sm-12">
                  <%= f.text_area :description, id: :accomodation_description, class: "form-control ckeditor" %>
                  <label>Description</label>
               </div>
            </div>
         </div>
         <!-- Add Location -->
         <div class="add-listing-box add-location mrg-bot-25 padd-bot-30 padd-top-25">
            <div class="listing-box-header">
               <i class="ti-location-pin theme-cl"></i>
               <h3>Add Location</h3>
               <p>Write Address Information about your accomodation Location</p>
            </div>
            <div class="row mrg-r-10 mrg-l-10">
               <div class="col-sm-6">
                  <label>Address</label>
                  <%= f.text_field :address, id: :accomodation_address, class: "form-control" %>
               </div>
               <div class="col-sm-6">
                  <label>City</label>
                  <%= f.text_field :city, id: :accomodation_city, class: "form-control" %>
               </div>
               <div class="col-sm-6">
                  <label>State</label>
                  <%= f.text_field :state, id: :accomodation_state, class: "form-control" %>
               </div>
               <div class="col-sm-6">
                  <label>Country</label>
                  <%= f.text_field :country, id: :accomodation_country, class: "form-control" %>
               </div>
               <div class="col-sm-6">
                  <label>Zip code</label>
                  <%= f.text_field :zipcode, id: :accomadation_zipcode, class: "form-control" %>
               </div>
            </div>
         </div>
         <!-- End Add Location -->
         <!-- Full Information -->
         <div class="add-listing-box full-detail mrg-bot-25 padd-bot-30 padd-top-25">
            <div class="listing-box-header">
               <i class="ti-write theme-cl"></i>
               <h3>Contact Information</h3>
               <p>Write contact information about accomodation</p>
            </div>
            <div class="row mrg-r-10 mrg-l-10">
               <div class="col-sm-6">
                  <label>Contact</label>
                  <%= f.text_field :contact, id: :accomodation_contact, class: "form-control" %>
               </div>
               <div class="col-sm-6">
                  <label>Email</label>
                  <%= f.text_field :email, id: :accomodation_email, class: "form-control" %>
               </div>
               <div class="col-sm-6">
                  <label>Website</label>
                  <%= f.text_field :website, id: :accomodation_website, class: "form-control" %>
               </div>
            </div>
         </div>
         <!-- End Full Information -->
         <div class="add-listing-box amenities mrg-bot-25 padd-bot-30 padd-top-25">
            <div class="listing-box-header">
               <i class="ti-gift theme-cl"></i>
               <h3>Amenities</h3>
               <p>Write something general information about your accomodation</p>
            </div>
            <div class="row mrg-r-10 mrg-l-10">
               <% @amenities.each do |amenity| %>
               <% if (@accomodation.id.present?) && (@accomodation.amenities.ids.include? amenity.id) %>
               <div class="col-sm-4">
                  <span class="custom-checkbox d-block">
                  <input type="checkbox" id="select<%= amenity.id%>" name="listing[amenity_remove][]" value="<%= amenity.id %>" checked>
                  <label for="select<%= amenity.id%>"></label>
                  <%= amenity.name %>
                  </span>
               </div>
               <% else %>
               <div class="col-sm-4">
                  <span class="custom-checkbox d-block">
                  <%= f.check_box(:amenities, {multiple: true}, amenity.id, nil)%>
                  <label for="select<%= amenity.id%>"></label>
                  <%= amenity.name %>
                  </span>
               </div>
               <% end %>
               <% end %>
            </div>
         </div>
         <div class="text-center">
            <%= f.submit "Submit Accommodation", class: "btn theme-btn" %>
         </div>
         <% end %>
      </div>
   </div>
</section>
<script type="text/javascript">
   $(document).ready(function(){
     $(".ckeditor").ckeditor({
     });
   });
</script>

app/views/accomodations/add_images.html.erb
<section class="detail-section" style="background:url('<%= @accomodation.banner_image.url %>')";>
   <div class="overlay" style="background-color: rgb(36, 36, 41); opacity: 0.5;">
   </div>
   <div class="profile-cover-content">
      <div class="container">
         <div class="cover-buttons">
            <ul>
               <li>
                  <div class="buttons medium button-plain ">
                     <i class="fa fa-phone"></i>
                     <%= @accomodation.contact %>
                  </div>
               </li>
               <li>
                  <div class="buttons medium button-plain ">
                     <i class="fa fa-map-marker"></i>
                     <%= @accomodation.address %>
                  </div>
               </li>
               <li>
                  <div class="inside-rating buttons listing-rating theme-btn button-plain">
                     <span class="value">9.7</span> 
                     <sup class="out-of">/10</sup>
                  </div>
               </li>
               <li>
                  <a href="#add-review" class="buttons btn-outlined medium add-review">
                  <i class="fa fa-comments-o"></i>
                  <span class="hidden-xs">Add review</span>
                  </a>
               </li>
               <li>
                  <a href="#" data-listing-id="74" data-nonce="01a769d424" class="buttons btn-outlined">
                  <i class="fa fa-heart-o">
                  </i>
                  <span class="hidden-xs">Bookmark</span> 
                  </a>
               </li>
            </ul>
         </div>
         <div class="listing-owner hidden-xs hidden-sm">
            <div class="listing-owner-avater">
               <%= image_tag "avatar.jpg", class: "img-responsive img-circle"%>
            </div>
            <div class="listing-owner-detail">
               <h4>Lucy Lukie</h4>
               <span class="theme-cl">Web Designer</span>
            </div>
         </div>
      </div>
   </div>
</section>
<div class="container">
   <div style="margin-top:50px;">
      <%= form_for :upload_images, url: :upload_accomodation_image_accomodations,  html: { multipart: true, class: "dropzone"} do |f|  %>
      <%= f.hidden_field :accomodation_id, value:  @accomodation.id %>
      <div class="fallback">
         <%= f.file_field :image %><br>
         <%= f.submit "Upload" %>
      </div>
      <% end %>
   </div>
   <%= link_to "Back to Accomodation", accomodation_path(@accomodation), class: "btn btn-success", style: "margin-left:10%;margin-bottom:50px;" %>
</div>
<script type="text/javascript">
   $(function () {
     $(".dropzone").dropzone({
       
       paramName: 'upload[image]',
       addRemoveLinks: true,
       success: function(file, response) {
         $(file.previewElement).find('.dz-remove').attr('id', response.id);
         $(file.previewElement).addClass('dz-success');
       },
       removedfile: function(file) {
         var id = $(file.previewTemplate).find('.dz-remove').attr('id');
         $.ajax({
           type: 'DELETE',
           url: "/remove_accomodation_image/" + id,
           success: function(data) {
             console.log(data.message);
           }
         });
         var previewElement;
         return (previewElement = file.previewElement) != null ? (previewElement.parentNode.removeChild(file.previewElement)) : (void 0);
       },
     });
   });
</script>

app/views/accomodations/edit.html.erb
<%= render 'form', accomodation: @accomodation %>

<%= link_to 'Show', accomodation_path(@accomodation) %> |
<%= link_to 'Back', accomodations_path %>

app/views/accomodations/index.html.erb
<div class="clearfix"></div>
<!-- ================ Start Page Title ======================= -->
<section class="title-transparent page-title" style="background:url('<%= asset_path("accommodation.jpg")%>')";>
   <div class="container">
   </div>
</section>
<div class="clearfix"></div>
<!-- ================ Profile Name Section ======================= -->
<section class="padd-0">
   <div class="container">
      <div class="col-md-12 translateY-60 col-sm-12">
         <!-- General Information -->
         <div class="add-listing-box edit-info mrg-bot-25 padd-bot-30 padd-top-25">
            <div class="listing-box-header">
               <div class="avater-box">
                  <%= image_tag "avatar.jpg", class: "img-responsive img-circle", alt: "" %>
                  <span class="avater-status status-pulse online"></span>
               </div>
               <h3>Daniel M. Dev</h3>
               <p>270 Listing</p>
            </div>
         </div>
         <!-- End General Information -->
      </div>
   </div>
</section>
<!-- ================ End Profile Name Section ======================= -->
<!-- ================ Start Manage Listing ======================= -->
<section class="manage-listing padd-top-0">
   <div class="container">
      <div class="col-md-12 col-sm-12">
         <!-- Filter Option -->
         <div class="row">
            <div class="col-md-8">
               <div class="row">
                  <div class="col-md-6">
                     <div class="form-group">
                        <label class="control-label col-xs-3">Sort By:</label>
                        <div class="col-xs-9">
                           <select class="form-control">
                              <option value="download_name_tag" selected="selected">Theme Name</option>
                              <option value="timestamp">Last Updated</option>
                           </select>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-6">
                     <div class="form-group">
                        <label class="control-label col-xs-3">Author:</label>
                        <div class="col-xs-9">
                           <select class="form-control">
                              <option value="download_name_tag" selected="selected">Theme Name</option>
                              <option value="timestamp">Last Updated</option>
                           </select>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <div class="col-md-4">
               <div class="full-right search-wrapper">
                  <input type="search" class="form-control" placeholder="Filter by keyword...">
               </div>
            </div>
         </div>
         <!-- End Filter Option -->
         <!-- Start All Listing List -->
         <div class="row">
            <% @accomodations.each do |accomodation| %>
            <div class="col-md-12">
               <div class="small-list-wrapper">
                  <%= link_to accomodation_path(accomodation), class: "listing-item" do %>
                  <ul>
                     <li>
                        <div class="small-listing-box light-gray">
                           <div class="small-list-img">
                              <%= image_tag accomodation.banner_image_url, class: "img-responsive" ,  style: "height:50px;width:100%;" if accomodation.banner_image_url.present? %>
                           </div>
                           <% end %> 
                           <!--                            <div class="small-list-detail">
                              <h4><#%= accomodation.name %></h4>
                              <p><a href="#" title="Food & restaurant">
                                 <#%= accomodation.accomodation_category.try(:name) %>
                                 </a>
                              </p>
                              </div>
                              -->
                           <div class="small-list-action">
                              <%= link_to edit_accomodation_path(accomodation), class: "light-gray-btn btn-square" do %>
                              <i class="fa fa-pencil"></i>
                              <% end %>
                              <%= link_to accomodation_path(accomodation), method: :delete, data: { confirm: 'Are you sure?' }, class: "theme-btn btn-square" do %>
                              <i class="fa fa-trash"></i>
                              <% end %>
                           </div>
                        </div>
                     </li>
                  </ul>
               </div>
            </div>
            <% end %>
         </div>
      </div>
   </div>
</section>
</div>
<!-- ================ End Start Manage Listing ======================= -->
<!-- ================ Start Footer ======================= -->
<footer class="footer dark-bg">
   <div class="row padd-0 mrg-0">
      <div class="footer-text">
         <div class="col-md-3 col-sm-12 theme-bg">
            <div class="footer-widget">
               <div class="textwidget">
                  <h3 class="widgettitle widget-title">Get In Touch</h3>
                  <p>7744 North Park Place<br>
                     San Francisco, CA 714258
                  </p>
                  <p><strong>Email:</strong> support@listinghub.com</p>
                  <p>
                     <strong>Call:</strong> <a href="tel:+774422777">777-444-2222</a>
                  </p>
               </div>
            </div>
         </div>
         <div class="col-md-5 col-sm-4">
            <div class="footer-widget">
               <h3 class="widgettitle widget-title">About Us</h3>
               <ul class="footer-navigation">
                  <li><a href="#">Home Version 1</a></li>
                  <li><a href="#">Home Version 2</a></li>
                  <li><a href="#">Home Version 3</a></li>
                  <li><a href="#">Home Version 4</a></li>
                  <li><a href="#">Listing Detail</a></li>
                  <li><a href="#">Listing Vertical</a></li>
                  <li><a href="#">Listing Sidebar</a></li>
                  <li><a href="#">Vertical Sidebar</a></li>
               </ul>
            </div>
         </div>
         <div class="col-md-4 col-sm-6">
            <div class="footer-widget">
               <h3 class="widgettitle widget-title">Connect Us</h3>
               <%= image_tag "footer-logo.png", class: "img-responsive", alt: "" %>
               <ul class="footer-social">
                  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                  <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                  <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
               </ul>
            </div>
         </div>
      </div>
   </div>
   <div class="footer-copyright">
      <p>Copyright@ 2017 Listing Hub Design By <a href="http://www.themezhub.com/" title="Themezhub" target="_blank">Themezhub</a></p>
   </div>
</footer>
<!-- ================ End Footer Section ======================= -->
<!-- Switcher -->
<button class="w3-button w3-teal w3-xlarge w3-right" onclick="openRightMenu()"><i class="spin theme-cl fa fa-cog" aria-hidden="true"></i></button>
<div class="w3-sidebar w3-bar-block w3-card-2 w3-animate-right" style="display:none;right:0;" id="rightMenu">
<button onclick="closeRightMenu()" class="w3-bar-item w3-button w3-large theme-bg">Close &times;</button>
<div class="title-logo">
   <%= image_tag "logo.png", class: "img-responsive", alt: "" %>
   <h4>Choose Your Color</h4>
</div>
<script>
   function openRightMenu() {
    document.getElementById("rightMenu").style.display = "block";
   }
   function closeRightMenu() {
    document.getElementById("rightMenu").style.display = "none";
   }
</script>
<script type="text/javascript">
   $(document).ready(function() {
    $('#styleOptions').styleSwitcher();
   });
</script>
<script>
   $(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip(); 
   });
</script>

app/views/accomodations/new.html.erb
<section class="title-transparent page-title" style="background:url('<%= asset_path("hotel-banner-.jpg")%>')">
  <div class="container">
    <div class="title-content">
      <h1>Add Accommodation</h1>
      <div class="breadcrumbs">
        <a href="/">Home</a>
        <span class="gt3_breadcrumb_divider"></span>
        <span class="current">Add Accommodation</span>
      </div>
    </div>
  </div>
</section>
<%= render 'form', accomodation: @accomodation %>

<%= link_to 'Back', accomodations_path %>