config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :accomodations 
  get '/search-listing' => "listing_search#search_listing"

  devise_for :users, controllers: {
    sessions: "users/sessions", 
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    confirmations: "users/confirmations"
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  resources :listings, only: [:show, :index]
  resources :places, only: [:show, :index]
  delete '/remove_listing_image/:id' => "listings#remove_listing_image"

  namespace :admins do 
    resources :amenities
    resources :listings 

    resources :listing_categories
    resources :place_categories
    resources :places do 
      collection do
        post :upload_place_image
      end
    end
  end

  namespace :users do 

        resources :listings do
          collection do
            post :upload_listing_image
          end
          member do 
            get :add_images
          end 
        end
        resources :accomodations do
          collection do
           post :upload_accomodation_image 
         end
         member do 
          get :add_images  
        end  
      end

    resources :accounts
    get '/my-account' => "accounts#my_account"

  end

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :place_category, optional: true
  has_many :images, as: :imageable, dependent: :destroy
  geocoded_by :full_address
  after_validation :geocode

  mount_uploader  :banner_image, ImageUploader

  def full_address
    "#{self.city} #{self.state} #{self.country} #{self.zipcode}"
  end

end

app/controllers/admins/places_controller.rb
class Admins::PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end
  
  def upload_place_image
   @places = Place.find(params[:upload_images][:place_id])
   @image = @places.images.build(image: params[:upload][:image])
   if @image.save!
     respond_to do |format|
       format.json{ render :json => @image }
     end
   end
 end
 def remove_place_image
   @image = Image.find(params[:id])
   if  @image .destroy
    render json: { message: "file delete from server"}
  else
   render json: {message: @image.errors.full_messages.join(", ") }
 end
end
def add_images
 @place = Place.find(params[:id])
end
  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to admins_place_path(@place), notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to admins_place_path(@place), notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to admins_places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :description, :banner_image, :city, :state, :country, :zipcode, :place_category_id)
    end
  end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_listing, only: [:show]

  layout 'listing'
  
  def index
    @places = Place.order(:name).page params[:page]
  end

  def show
    @latest_place = Place.last(5)


    @place_categories = PlaceCategory.all
    
    # Nearby Listings to this place

    @near_by_listings = Listing.near([@place.latitude, @place.longitude], 20, units: :km)

    # Nearby Accommodations to this place

    @near_by_accomodations = Accomodation.near([@place.latitude, @place.longitude], 20, units: :km)

  end

  private

    def set_listing
      @place = Place.find(params[:id])
    end

end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/admins/places/_form.html.erb
<%= form_with(model: [:admins, place], local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :place_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :place_description %>
  </div>

  <div class="field">
    <%= form.label :banner_image %>
    <%= form.file_field :banner_image, id: :place_banner_image %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :place_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :place_state %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :place_country %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode, id: :place_zipcode %>
  </div>

  <div class="field">
    <%= form.label :place_category_id %>
    <%= form.select :place_category_id, options_for_select(PlaceCategory.all.collect{ |u| [u.name, u.id] }, (form.object.try(:place_category_id))), {prompt: "Select Place Category"}, {class: "form-control"} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', admins_place_path(@place) %> |
<%= link_to 'Back', admins_places_path %>

app/views/admins/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Banner image</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Zipcode</th>
      <th>Place category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.description %></td>
        <td><%= place.banner_image %></td>
        <td><%= place.city %></td>
        <td><%= place.state %></td>
        <td><%= place.country %></td>
        <td><%= place.zipcode %></td>
        <td><%= place.place_category.try(:name) %></td>
        <td><%= link_to 'Show', admins_place_path(place) %></td>
        <td><%= link_to 'Edit', edit_admins_place_path(place) %></td>
        <td><%= link_to 'Destroy', admins_place_path(place), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_admins_place_path %>

app/views/admins/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', admins_places_path %>

app/views/admins/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @place.description %>
</p>

<p>
  <strong>Banner image:</strong>
  <%= @place.banner_image %>
</p>

<p>
  <strong>City:</strong>
  <%= @place.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @place.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @place.country %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @place.zipcode %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<p>
  <strong>Place category:</strong>
  <%= @place.place_category %>
</p>

<div class="container">
   <div style="margin-top:50px;">
      <%= form_for :upload_images, url: :upload_place_image_admins_places,  html: { multipart: true, class: "dropzone"} do |f|  %>
      <%= f.hidden_field :place_id, value:  @place.id %>
      <div class="fallback">
         <%= f.file_field :image %><br>
         <%= f.submit "Upload" %>
      </div>
      <% end %>
   </div>
   <%= link_to "Back to Listing", place_path(@place), class: "btn btn-success", style: "margin-left:10%;margin-bottom:50px;" %>
</div>
<script type="text/javascript">
   $(function () {
     $(".dropzone").dropzone({
       
       paramName: 'upload[image]',
       addRemoveLinks: true,
       success: function(file, response) {
         $(file.previewElement).find('.dz-remove').attr('id', response.id);
         $(file.previewElement).addClass('dz-success');
       },
       removedfile: function(file) {
         var id = $(file.previewTemplate).find('.dz-remove').attr('id');
         $.ajax({
           type: 'DELETE',
           url: "/remove_listing_image/" + id,
           success: function(data) {
             console.log(data.message);
           }
         });
         var previewElement;
         return (previewElement = file.previewElement) != null ? (previewElement.parentNode.removeChild(file.previewElement)) : (void 0);
       },
     });
   });
</script>


<%= link_to 'Edit', edit_admins_place_path(@place) %> |
<%= link_to 'Back', admins_places_path %>