config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :accomodations 
  get '/search-listing' => "listing_search#search_listing"

  devise_for :users, controllers: {
    sessions: "users/sessions", 
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    confirmations: "users/confirmations"
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  resources :listings, only: [:show, :index]
  resources :places, only: [:show, :index]
  delete '/remove_listing_image/:id' => "listings#remove_listing_image"

  namespace :admins do 
    resources :amenities
    resources :listings 

    resources :listing_categories
    resources :place_categories
    resources :places do 
      collection do
        post :upload_place_image
      end
    end
  end

  namespace :users do 

        resources :listings do
          collection do
            post :upload_listing_image
          end
          member do 
            get :add_images
          end 
        end
        resources :accomodations do
          collection do
           post :upload_accomodation_image 
         end
         member do 
          get :add_images  
        end  
      end

    resources :accounts
    get '/my-account' => "accounts#my_account"

  end

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :listing_category, optional: true
  belongs_to :user, optional: true
  has_many :images, as: :imageable, dependent: :destroy
  has_many :listing_amenities
  has_many :amenities, through: :listing_amenities
  has_many :working_hours, dependent: :destroy
  geocoded_by :full_address
  after_validation :geocode

  has_many :reviews, as: :reviewable 

  mount_uploader :banner_image, ImageUploader

  accepts_nested_attributes_for :working_hours, reject_if: :all_blank, allow_destroy: true
  
  paginates_per 5

  def full_address
    "#{self.city} #{self.state} #{self.country} #{self.zipcode}"
  end
end

app/controllers/admins/listings_controller.rb
class Admins::ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to admins_listing_path(@listing), notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to admins_listing_path(@listing), notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to admins_listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :banner_image, :city, :state, :country, :zipcode, :latitude, :longitude, :contact, :email, :website, :address, :fb_url, :linkedin_url, :gplus_url, :twitter_url, :listing_category_id)
    end
  end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show]

  layout 'listing'
  
  def index
    @listings = Listing.order(:name).page params[:page]
  end

  def show
    @latest_listings = Listing.last(5)
  end

  private

    def set_listing
      @listing = Listing.find(params[:id])
    end

end

app/controllers/users/listings_controller.rb
class Users::ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  layout 'listing'
  # GET /listings
  # GET /listings.json
  def index
   @listings = current_user.listings
 end
  # GET /listings/1
  # GET /listings/1.json
  def show
   @latest_listings = Listing.last(5)
 end
  # GET /listings/new
  def new
   @listing = Listing.new
   @amenities = Amenity.all
   @working_hours  = WorkingHour.new
 end
  # GET /listings/1/edit
  def edit
   @listings = Listing.all
   @amenities = Amenity.all
 end
 def upload_listing_image
   @listings = Listing.find(params[:upload_images][:listing_id])
   @image = @listings.images.build(image: params[:upload][:image])
   if @image.save!
     respond_to do |format|
       format.json{ render :json => @image }
     end
   end
 end
 def remove_listing_image
   @image = Image.find(params[:id])
   if  @image .destroy
    render json: { message: "file delete from server"}
  else
   render json: {message: @image.errors.full_messages.join(", ") }
 end
end
def add_images
 @listing = Listing.find(params[:id])
end
  # POST /listings
  # POST /listings.json
  def create
   @listing = Listing.new(listing_params)
   respond_to do |format|
    if @listing.save
      format.html { redirect_to users_listing_path(@listing), notice: 'Listing was successfully created.' }
      format.json { render :show, status: :created, location: @listing }
    else
      format.html { render :new }
      format.json { render json: @listing.errors, status: :unprocessable_entity }
    end
  end
end
  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to users_listing_path(@listing), notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
       format.html { render :edit }
       format.json { render json: @listing.errors, status: :unprocessable_entity }
     end
   end
 end
  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
   @listing.destroy
   respond_to do |format|
     format.html { redirect_to users_listings_url, notice: 'Listing was successfully destroyed.' }
     format.json { head :no_content }
   end
 end
 private
  # Use callbacks to share common setup or constraints between actions.
  def set_listing
    @listing = Listing.find(params[:id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def listing_params
    params.require(:listing).permit(:name, :description, :banner_image, :city, :state, :country, :zipcode, :latitude, :longitude, :contact, :email, :website, :address, :fb_url, :linkedin_url, :gplus_url, :twitter_url, :listing_category_id ,images_attributes: [:id,:image, :imageable_id, :imageable_type, :_destroy])
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users/listings_helper.rb
module Users::ListingsHelper
end

app/views/admins/listings/_form.html.erb
<%= form_with(model: [:admins, listing], local: true) do |form| %>
<% if listing.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

  <ul>
    <% listing.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name, id: :listing_name %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_area :description, id: :listing_description %>
</div>

<div class="field">
  <%= form.label :banner_image %>
  <%= form.text_field :banner_image, id: :listing_banner_image %>
</div>

<div class="field">
  <%= form.label :city %>
  <%= form.text_field :city, id: :listing_city %>
</div>

<div class="field">
  <%= form.label :state %>
  <%= form.text_field :state, id: :listing_state %>
</div>

<div class="field">
  <%= form.label :country %>
  <%= form.text_field :country, id: :listing_country %>
</div>

<div class="field">
  <%= form.label :zipcode %>
  <%= form.text_field :zipcode, id: :listing_zipcode %>
</div>

<div class="field">
  <%= form.label :contact %>
  <%= form.text_field :contact, id: :listing_contact %>
</div>

<div class="field">
  <%= form.label :email %>
  <%= form.text_field :email, id: :listing_email %>
</div>

<div class="field">
  <%= form.label :website %>
  <%= form.text_field :website, id: :listing_website %>
</div>

<div class="field">
  <%= form.label :address %>
  <%= form.text_field :address, id: :listing_address %>
</div>

<div class="field">
  <%= form.label :fb_url %>
  <%= form.text_field :fb_url, id: :listing_fb_url %>
</div>

<div class="field">
  <%= form.label :linkedin_url %>
  <%= form.text_field :linkedin_url, id: :listing_linkedin_url %>
</div>

<div class="field">
  <%= form.label :gplus_url %>
  <%= form.text_field :gplus_url, id: :listing_gplus_url %>
</div>

<div class="field">
  <%= form.label :twitter_url %>
  <%= form.text_field :twitter_url, id: :listing_twitter_url %>
</div>

<div class="field">
  <%= form.label :listing_category_id %>
  <%= form.select :listing_category_id, options_for_select(ListingCategory.all.collect{ |u| [u.name, u.id] }, (form.object.try(:listing_category_id))), {prompt: "Select Listing Category"}, {} %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/admins/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', admins_listing_path(@listing) %> |
<%= link_to 'Back', admins_listings_path %>

app/views/admins/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Banner image</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Zipcode</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Contact</th>
      <th>Email</th>
      <th>Website</th>
      <th>Address</th>
      <th>Fb url</th>
      <th>Linkedin url</th>
      <th>Gplus url</th>
      <th>Twitter url</th>
      <th>Listing category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
    <tr>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td><%= listing.banner_image %></td>
      <td><%= listing.city %></td>
      <td><%= listing.state %></td>
      <td><%= listing.country %></td>
      <td><%= listing.zipcode %></td>
      <td><%= listing.latitude %></td>
      <td><%= listing.longitude %></td>
      <td><%= listing.contact %></td>
      <td><%= listing.email %></td>
      <td><%= listing.website %></td>
      <td><%= listing.address %></td>
      <td><%= listing.fb_url %></td>
      <td><%= listing.linkedin_url %></td>
      <td><%= listing.gplus_url %></td>
      <td><%= listing.twitter_url %></td>
      <td><%= listing.listing_category %></td>
      <td><%= link_to 'Show', admins_listing_path(listing) %></td>
      <td><%= link_to 'Edit', edit_admins_listing_path(listing) %></td>
      <td><%= link_to 'Destroy', admins_listing_path(listing), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_admins_listing_path %>

app/views/admins/listings/new.html.erb
<%= render 'form', listing: @listing %>

<%= link_to 'Back', admins_listings_path %>

app/views/admins/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Banner image:</strong>
  <%= @listing.banner_image %>
</p>

<p>
  <strong>City:</strong>
  <%= @listing.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @listing.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @listing.country %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @listing.zipcode %>
a</p>

<p>
  <strong>Latitude:</strong>
  <%= @listing.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @listing.longitude %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @listing.contact %>
</p>

<p>
  <strong>Email:</strong>
  <%= @listing.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @listing.website %>
</p>

<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>Fb url:</strong>
  <%= @listing.fb_url %>
</p>

<p>
  <strong>Linkedin url:</strong>
  <%= @listing.linkedin_url %>
</p>

<p>
  <strong>Gplus url:</strong>
  <%= @listing.gplus_url %>
</p>

<p>
  <strong>Twitter url:</strong>
  <%= @listing.twitter_url %>
</p>

<p>
  <strong>Listing category:</strong>
  <%= @listing.listing_category %>
</p>

<%= link_to 'Edit', edit_admins_listing_path(@listing) %> |
<%= link_to 'Back', admins_listings_path %>