config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :accomodations 
  get '/search-listing' => "listing_search#search_listing"

  devise_for :users, controllers: {
    sessions: "users/sessions", 
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    confirmations: "users/confirmations"
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  resources :listings, only: [:show, :index]
  resources :places, only: [:show, :index]
  delete '/remove_listing_image/:id' => "listings#remove_listing_image"

  namespace :admins do 
    resources :amenities
    resources :listings 

    resources :listing_categories
    resources :place_categories
    resources :places do 
      collection do
        post :upload_place_image
      end
    end
  end

  namespace :users do 

        resources :listings do
          collection do
            post :upload_listing_image
          end
          member do 
            get :add_images
          end 
        end
        resources :accomodations do
          collection do
           post :upload_accomodation_image 
         end
         member do 
          get :add_images  
        end  
      end

    resources :accounts
    get '/my-account' => "accounts#my_account"

  end

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/place_category.rb
class PlaceCategory < ApplicationRecord
    validates :name, :description, presence: true
    has_many :places, dependent: :destroy
    mount_uploader :banner_image, ImageUploader
end

app/controllers/admins/place_categories_controller.rb
class Admins::PlaceCategoriesController < ApplicationController
  before_action :set_place_category, only: [:show, :edit, :update, :destroy]

  # GET /place_categories
  # GET /place_categories.json
  def index
    @place_categories = PlaceCategory.all
  end

  # GET /place_categories/1
  # GET /place_categories/1.json
  def show
     @place = Place.includes(:place_category).find(params[:id])
  end

  # GET /place_categories/new
  def new
    @place_category = PlaceCategory.new
  end

  # GET /place_categories/1/edit
  def edit
  end

  # POST /place_categories
  # POST /place_categories.json
  def create
    @place_category = PlaceCategory.new(place_category_params)

    respond_to do |format|
      if @place_category.save
        format.html { redirect_to admins_place_category_path(@place_category), notice: 'Place category was successfully created.' }
        format.json { render :show, status: :created, location: @place_category }
      else
        format.html { render :new }
        format.json { render json: @place_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /place_categories/1
  # PATCH/PUT /place_categories/1.json
  def update
    respond_to do |format|
      if @place_category.update(place_category_params)
        format.html { redirect_to admins_place_category_path(@place_category), notice: 'Place category was successfully updated.' }
        format.json { render :show, status: :ok, location: @place_category }
      else
        format.html { render :edit }
        format.json { render json: @place_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /place_categories/1
  # DELETE /place_categories/1.json
  def destroy
    @place_category.destroy
    respond_to do |format|
      format.html { redirect_to admins_place_categories_url, notice: 'Place category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place_category
      @place_category = PlaceCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_category_params
      params.require(:place_category).permit(:name, :description, :banner_image)
    end
end

app/helpers/place_categories_helper.rb
module PlaceCategoriesHelper
end

app/views/admins/place_categories/_form.html.erb
<%= form_with(model:[:admins, place_category], local: true) do |form| %>
  <% if place_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place_category.errors.count, "error") %> prohibited this place_category from being saved:</h2>

      <ul>
      <% place_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :place_category_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :place_category_description %>
  </div>

  <div class="field">
    <%= form.label :banner_image %>
    <%= form.file_field :banner_image, id: :place_category_banner_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/place_categories/edit.html.erb
<h1>Editing Place Category</h1>

<%= render 'form', place_category: @place_category %>

<%= link_to 'Show', admins_place_category_path(@place_category) %> |
<%= link_to 'Back', admins_place_categories_path %>

app/views/admins/place_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Place Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Banner image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @place_categories.each do |place_category| %>
      <tr>
        <td><%= place_category.name %></td>
        <td><%= place_category.description %></td>
        <td><%= place_category.banner_image %></td>
        <td><%= link_to 'Show', admins_place_category_path(place_category) %></td>
        <td><%= link_to 'Edit', edit_admins_place_category_path(place_category) %></td>
        <td><%= link_to 'Destroy', admins_place_category_path(place_category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place Category', new_admins_place_category_path %>

app/views/admins/place_categories/new.html.erb
<h1>New Place Category</h1>

<%= render 'form', place_category: @place_category %>

<%= link_to 'Back', admins_place_categories_path %>

app/views/admins/place_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place_category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @place_category.description %>
</p>

<p>
  <strong>Banner image:</strong>
  <%= @place_category.banner_image %>
</p>

<%= link_to 'Edit', edit_admins_place_category_path(@place_category) %> |
<%= link_to 'Back', admins_place_categories_path %>